# Generated by Django 5.1.4 on 2026-02-26 22:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('median_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('census_data', models.JSONField(blank=True, default=dict)),
                ('last_census_updated', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('site_type', models.CharField(choices=[('SEEKING', 'Seeking City Directory'), ('INDUSTRY', 'Industry-Specific Directory'), ('MARKETING', 'Marketing Site'), ('EDUCATIONAL', 'Educational Hub')], max_length=20)),
                ('display_name', models.CharField(max_length=255)),
                ('primary_color', models.CharField(default='#0078D4', max_length=7)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('NEWS', 'Local News'), ('EVENTS', 'Events & Activities'), ('BUSINESS', 'Business & Economy'), ('GOVERNMENT', 'Government & Politics'), ('EDUCATION', 'Education'), ('LIFESTYLE', 'Lifestyle & Culture'), ('REAL_ESTATE', 'Real Estate & Construction'), ('GUIDE', 'City Guide')], max_length=20)),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_model_used', models.CharField(default='gpt-4', max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('prompt_used', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('view_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.city')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.site')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('organizer', models.CharField(blank=True, max_length=255)),
                ('event_url', models.URLField(blank=True)),
                ('ticket_url', models.URLField(blank=True)),
                ('ai_scraped', models.BooleanField(default=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.city')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.site')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='sites',
            field=models.ManyToManyField(related_name='cities', to='core.site'),
        ),
        migrations.CreateModel(
            name='ContentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('avg_time_on_page', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'site', 'article')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state', 'country')},
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300)),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'Construction & Contractors'), ('LANDSCAPING', 'Landscaping & Lawn Care'), ('REAL_ESTATE', 'Real Estate'), ('RESTAURANT', 'Restaurant & Dining'), ('RETAIL', 'Retail & Shopping'), ('SERVICES', 'Professional Services'), ('HEALTHCARE', 'Healthcare'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment & Arts'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('FREE', 'Free Listing'), ('PREMIUM', 'Premium ($50/month)'), ('FEATURED', 'Featured ($150/month)')], default='FREE', max_length=10)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('photos', models.JSONField(blank=True, default=list)),
                ('featured_until', models.DateField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.city')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='core.site')),
            ],
            options={
                'ordering': ['-tier', '-featured_until', 'name'],
                'unique_together': {('site', 'slug')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_date'], name='core_articl_publish_f7f6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['city', '-published_date'], name='core_articl_city_id_909366_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', '-published_date'], name='core_articl_site_id_469018_idx'),
        ),
    ]
