# Generated by Django 5.1.4 on 2026-02-27 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('state_flower', models.CharField(blank=True, max_length=100)),
                ('state_tree', models.CharField(blank=True, max_length=100)),
                ('state_bird', models.CharField(blank=True, max_length=100)),
                ('state_motto', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state_abbr',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.state'),
        ),
    ]
