# Generated by Django 5.1.4 on 2026-03-13 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cityimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid — Awaiting Fulfillment'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_name', models.CharField(blank=True, max_length=255)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('HOME', 'Home & Garden'), ('CLOTHING', 'Clothing & Accessories'), ('FOOD', 'Food & Beverage'), ('ELECTRONICS', 'Electronics'), ('SPORTS', 'Sports & Outdoors'), ('SERVICES', 'Services'), ('AUTOMOTIVE', 'Automotive'), ('KIDS', 'Kids & Baby'), ('COLLECTIBLES', 'Collectibles & Antiques'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used – Like New'), ('GOOD', 'Used – Good'), ('FAIR', 'Used – Fair'), ('DIGITAL', 'Digital / Service')], default='NEW', max_length=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/')),
                ('quantity_available', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('ai_flagged', models.BooleanField(default=False)),
                ('ai_flag_reason', models.CharField(blank=True, max_length=500)),
                ('view_count', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='cityimage',
            new_name='core_cityim_city_id_20d9b9_idx',
            old_name='core_cityim_city_id_idx',
        ),
        migrations.RenameIndex(
            model_name='cityimage',
            new_name='core_cityim_is_appr_0c427b_idx',
            old_name='core_cityim_approve_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.site'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.business'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
        ),
        migrations.AddField(
            model_name='product',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.business'),
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.city'),
        ),
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.site'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['business', 'is_active', 'is_approved'], name='core_produc_busines_6bdef5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['city', 'is_active', 'is_approved'], name='core_produc_city_id_ec05ba_idx'),
        ),
    ]
