# Generated by Django 5.1.4 on 2026-03-13 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feed_url', models.URLField()),
                ('feed_type', models.CharField(choices=[('ICAL', 'iCalendar (.ics)'), ('RSS', 'RSS / Atom Feed'), ('SOCRATA', 'Socrata Open Data API'), ('HTML', 'HTML Scrape')], default='ICAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('municipal_office_name', models.CharField(blank=True, max_length=255)),
                ('municipal_office_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('avg_time_on_page', models.IntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estimated_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'site', 'article')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.eventsource'),
        ),
        migrations.DeleteModel(
            name='ContentPerformance',
        ),
    ]
