# Generated by Django 5.1.4 on 2026-03-19 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('agency', models.CharField(help_text='Issuing agency or organization', max_length=200)),
                ('bid_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(default='MO', max_length=2)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open — Accepting Bids'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated project value in dollars', max_digits=14, null=True)),
                ('external_url', models.URLField(blank=True, help_text='Link to official bid document')),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bid Opportunities',
                'ordering': ['due_date', '-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='PermitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(default='Springfield', max_length=100)),
                ('state', models.CharField(default='MO', max_length=2)),
                ('permit_type', models.CharField(help_text='e.g., Commercial Build, Residential, Demolition', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='e.g., Active, Finaled, Expired', max_length=50)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Source of public record')),
            ],
            options={
                'verbose_name_plural': 'Permit Records',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(help_text='Street address or intersection', max_length=300)),
                ('city', models.CharField(default='St. Louis', max_length=100)),
                ('state', models.CharField(default='MO', max_length=2)),
                ('description', models.TextField()),
                ('contractor', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, help_text='Project owner or client', max_length=200)),
                ('architect', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active / Under Construction'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=400)),
                ('taken_date', models.DateField(blank=True, help_text='Date photo was taken', null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('featured', models.BooleanField(default=False, help_text='Use as project cover photo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='construction.project')),
            ],
            options={
                'ordering': ['order', 'taken_date'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='construction.projectcategory'),
        ),
    ]
