# Generated by Django 5.1.4 on 2026-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('hand_tools', 'Hand Tools'), ('power_tools', 'Power Tools'), ('software', 'Software & CAD'), ('safety', 'Safety & PPE'), ('apparel', 'Work Apparel'), ('equipment', 'Heavy Equipment'), ('materials', 'Building Materials'), ('other', 'Other')], default='other', max_length=20)),
                ('affiliate_url', models.URLField(help_text='Tracking URL with your affiliate ID')),
                ('tagline', models.CharField(blank=True, help_text='Short value proposition', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('commission_rate', models.CharField(blank=True, help_text='e.g., "8%" or "4-6%"', max_length=50)),
                ('logo_url', models.URLField(blank=True, help_text='External logo image URL')),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in homepage sidebar')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Affiliates',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
