# Generated by Django 5.1.4 on 2026-03-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_add_affiliate_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Majestic Hotel → Majestic Condos"', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('current_name', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('original_building_type', models.CharField(choices=[('hotel', 'Hotel'), ('office', 'Office Building'), ('warehouse', 'Warehouse / Industrial'), ('retail', 'Retail / Department Store'), ('mixed', 'Mixed Use'), ('bank', 'Bank / Financial'), ('school', 'School / University'), ('other', 'Other')], max_length=20)),
                ('conversion_type', models.CharField(choices=[('residential', 'Residential (Apartments / Condos)'), ('mixed_residential', 'Mixed Use with Residential'), ('commercial', 'Commercial Redevelopment'), ('hospitality', 'Hospitality')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('planned', 'Planned / Approved'), ('stalled', 'Stalled')], default='completed', max_length=20)),
                ('original_units', models.IntegerField(blank=True, help_text='Hotel rooms, building floors, or sq ft', null=True)),
                ('original_unit_label', models.CharField(default='rooms', help_text='rooms / sq ft / floors / suites', max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('residential_units', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(choices=[('condo', 'Condominiums'), ('apartment', 'Apartments'), ('mixed', 'Mixed Condo / Apartment')], default='apartment', max_length=20)),
                ('completion_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('developer', models.CharField(blank=True, max_length=200)),
                ('architect', models.CharField(blank=True, max_length=200)),
                ('general_contractor', models.CharField(blank=True, max_length=200)),
                ('cover_image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True, help_text='SLDC, news article, or permit source URL')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Building Conversion',
                'verbose_name_plural': 'Building Conversions',
                'ordering': ['-completion_year', 'neighborhood', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('district', models.CharField(choices=[('downtown', 'Downtown'), ('midtown', 'Midtown / Grand Center'), ('northside', 'North Side'), ('southside', 'South Side'), ('central_west_end', 'Central West End'), ('slu_corridor', 'SLU / Grand Center Corridor'), ('bjc_corridor', 'BJC / Forest Park Medical Corridor'), ('lafayette_sq', 'Lafayette Square'), ('soulard', 'Soulard'), ('benton_park', 'Benton Park'), ('tower_grove', 'Tower Grove'), ('other', 'Other')], default='downtown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('crime_index', models.DecimalField(blank=True, decimal_places=1, help_text='Relative crime index (100 = national average)', max_digits=5, null=True)),
                ('walk_score', models.IntegerField(blank=True, help_text='Walk Score 0–100', null=True)),
                ('transit_score', models.IntegerField(blank=True, help_text='Transit Score 0–100', null=True)),
                ('nearby_universities', models.JSONField(blank=True, default=list, help_text='e.g. ["SLU", "UMSL", "WashU"]')),
                ('nearby_hospitals', models.JSONField(blank=True, default=list, help_text='e.g. ["Barnes-Jewish", "SSM Health"]')),
                ('grocery_stores', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Neighborhoods',
                'ordering': ['district', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TIFDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district_number', models.CharField(blank=True, max_length=50)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total TIF amount authorized', max_digits=14, null=True)),
                ('term_years', models.IntegerField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('sldc_url', models.URLField(blank=True, help_text='SLDC public records URL')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'TIF District',
                'verbose_name_plural': 'TIF Districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConversionFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('purchase_year', models.IntegerField(blank=True, null=True)),
                ('assessed_value_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('assessed_value_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rehab_cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_project_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('tif_amount', models.DecimalField(blank=True, decimal_places=2, help_text='TIF subsidy amount', max_digits=14, null=True)),
                ('historic_tax_credits', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nmtc_amount', models.DecimalField(blank=True, decimal_places=2, help_text='New Markets Tax Credits', max_digits=14, null=True)),
                ('other_incentives', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('avg_sale_price', models.DecimalField(blank=True, decimal_places=2, help_text='Average condo sale price', max_digits=14, null=True)),
                ('avg_rent_monthly', models.DecimalField(blank=True, decimal_places=2, help_text='Average monthly rent', max_digits=8, null=True)),
                ('avg_hoa_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_property_tax_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_confidence', models.CharField(choices=[('high', 'High — Public Records'), ('medium', 'Medium — News / Press Release'), ('estimate', 'Estimated / Derived')], default='medium', max_length=10)),
                ('data_sources', models.TextField(blank=True, help_text='Sources: SLDC, STLToday, permit records…')),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='construction.buildingconversion')),
            ],
            options={
                'verbose_name': 'Conversion Financials',
                'verbose_name_plural': 'Conversion Financials',
            },
        ),
        migrations.AddField(
            model_name='buildingconversion',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='construction.neighborhood'),
        ),
        migrations.AddField(
            model_name='buildingconversion',
            name='tif_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='construction.tifdistrict'),
        ),
    ]
