# Generated by Django 5.1.4 on 2026-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0003_stl_conversions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingconversion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
