# Generated by Django 5.1.4 on 2026-03-21 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_slug_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('scout', 'Scout'), ('analyst', 'Analyst'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_annual', models.DecimalField(decimal_places=2, default=0, help_text='Annual price (shown as /yr)', max_digits=8)),
                ('stripe_price_id_monthly', models.CharField(blank=True, help_text='Stripe Price ID for monthly billing', max_length=100)),
                ('stripe_price_id_annual', models.CharField(blank=True, help_text='Stripe Price ID for annual billing', max_length=100)),
                ('show_financials', models.BooleanField(default=False, help_text='Access to TIF, tax credit, rehab cost data')),
                ('show_comparables', models.BooleanField(default=False, help_text='Access to comparable sale/rent analysis')),
                ('show_powerbi', models.BooleanField(default=False, help_text='Embedded Power BI dashboards')),
                ('api_access', models.BooleanField(default=False, help_text='REST API access for bulk data export')),
                ('custom_reports', models.BooleanField(default=False, help_text='Custom on-demand analysis reports')),
                ('max_reports_monthly', models.IntegerField(default=0, help_text='0 = unlimited; custom report quota')),
                ('highlight', models.BooleanField(default=False, help_text='Mark as "Most Popular" on pricing page')),
                ('features_list', models.JSONField(blank=True, default=list, help_text='Ordered list of bullet points shown on pricing card')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='construction.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
            },
        ),
    ]
