# Generated by Django 5.1.4 on 2026-03-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Downtown Hotel Conversions Financial Overview"', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('scope', models.CharField(choices=[('building', 'Building Conversion'), ('neighborhood', 'Neighborhood'), ('citywide', 'Citywide / Statewide'), ('custom', 'Custom / Client-Specific')], default='citywide', max_length=20)),
                ('embed_mode', models.CharField(choices=[('public', 'Public — Publish to Web iframe'), ('private', 'Private — Azure AD Embed Token (subscriber-gated)')], default='private', max_length=10)),
                ('workspace_id', models.CharField(blank=True, help_text='Power BI Workspace (Group) ID — from URL: app.powerbi.com/groups/{workspace_id}', max_length=100)),
                ('report_id', models.CharField(blank=True, help_text='Power BI Report ID — from URL: .../reports/{report_id}', max_length=100)),
                ('dataset_id', models.CharField(blank=True, help_text='Power BI Dataset ID (needed for embed token generation)', max_length=100)),
                ('public_embed_url', models.URLField(blank=True, help_text='Full iframe src from Power BI "Publish to web" — used when embed_mode=public', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('default_height_px', models.IntegerField(default=600)),
                ('min_tier', models.CharField(choices=[('scout', 'Scout (free)'), ('analyst', 'Analyst ($29/mo)'), ('professional', 'Professional ($149/mo)'), ('enterprise', 'Enterprise ($499/mo)')], default='professional', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on the STL Conversions overview page')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbi_reports', to='construction.buildingconversion')),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbi_reports', to='construction.neighborhood')),
            ],
            options={
                'verbose_name': 'Power BI Report',
                'verbose_name_plural': 'Power BI Reports',
                'ordering': ['scope', 'name'],
            },
        ),
    ]
